### ISSUE TITLE
add spicord support pls

### ISSUE THREAD

**Issue by Luisitohh** [KASUNHapangama/DiscordLeaderboards#15]
I ask for spicord support because it is a plugin that can go on a bungeecord or spigot and it does not consume anything, it is enough to turn on a discord bot for any plugin, and DiscordSRV is very heavy even if I disable some options the plugin is still heavy for what needed.

Link: https://www.spigotmc.org/resources/spicord.64918/

**Comment by KASUNHapangama** [comment]
**Thank You for Suggestion** 
IF this reached more that 5 thumbs ups ill add that to the plugin

**Comment by KASUNHapangama** [comment]
Suggestion Accepted - Will be implemented in future 
Check Status : https://trello.com/b/3nEM0ADF/dleaderboard
