### ISSUE TITLE
Cannot create leaderboards in discord, errors out

### ISSUE THREAD

**Issue by LadyHaley** [KASUNHapangama/DiscordLeaderboards#19]
**Describe the bug**
When I try the leaderboard command, which shows as a registered command in discord, for a leaderboard ive created, it does not work. Discord says its unable to perform the action and i get an error in the server logs.

**To Reproduce**
1. Create Scoreboard in game
2. run the learderboard command in discord, I have given the bot the permissions it needs
3. get told it cant perform the action
4. error log, two errors for first and second attempt
`[23:26:47 ERROR]: [DiscordSRV] DiscordSRV encountered an unknown Discord error: 10062: Unknown interaction
[23:27:30 ERROR]: [DiscordSRV] DiscordSRV encountered an unknown Discord error: 40060: Interaction has already been acknowledged.`

**Expected behavior**
Leaderboard gets created

**Screenshots**
![image](https://github.com/KASUNHapangama/DiscordLeaderboards/assets/3754909/2a65ba58-c943-485d-a93d-5b849e3ae4b5)
![image](https://github.com/KASUNHapangama/DiscordLeaderboards/assets/3754909/3bc6f6f3-c663-4362-bd2f-e53f6d11992a)

**Desktop (please complete the following information):**
 - OS: Unraid OS running Pufferpanel in a docker container running Java 17 and paper version 540 for the server.
 
![image](https://github.com/KASUNHapangama/DiscordLeaderboards/assets/3754909/4f86bbd1-6d52-4384-8472-93f7e40cc270)
![image](https://github.com/KASUNHapangama/DiscordLeaderboards/assets/3754909/efb5f518-01d6-41d2-a066-158d2812962b)

 

**Additional context**

**Comment by LadyHaley** [comment]
[latest.log](https://github.com/KASUNHapangama/DiscordLeaderboards/files/11621869/latest.log)
Here is my log file

**Comment by KASUNHapangama** [comment]
You did grate job on Describing the issue, Thanks issue will be resolved within few hrs

**Comment by LadyHaley** [comment]
Yee i had done that yesterday. I was seemingly having some unrelated issue that was preventing discordsrv from properly functioning, I have since fixed that issue tho.

I am still having some issues with DL tho.
I have sound a conflict with the plugin DiscordSRVUtils, they both have leaderboard commands and causes issues and does not display correctly in discord.

the second issue im having, which doesnt seem like it affects functionality but i thought i should report anyway.
With DiscordSRVUtils disabled, when using the leaderboard command in the discord server, it seems to correctly create the leader board, by I got this error in my console also, but no error showed in discord
`[03:35:46 ERROR]: [DiscordSRV] Slash command "/leaderboard" was not acknowledged by DiscordLeaderboards's handler! The command will show as failed on Discord until this is fixed!`

**Comment by LadyHaley** [comment]
Just in case this doesnt look right for a default board, here is a picture of the created leaderboard
![image](https://github.com/KASUNHapangama/DiscordLeaderboards/assets/3754909/20dec687-e875-4b9e-9e94-02f0b9fa5ec0)

**Comment by LadyHaley** [comment]
Id love to leave a spigot review but im still waiting for the issue preventing me using the plugin from being resolved, any updates on the horizen?

**Comment by KASUNHapangama** [comment]
i have waited for while for stack up new features and bugfixes to next major update.. since you are waiting ill fix this issue and push it as hotfix today.

**Comment by KASUNHapangama** [comment]
I made fix just for you you can download it from [here](https://1drv.ms/u/s!AqO0dMDA_9vJgY0Vm6tilGnMEA1OWg?e=1v64eu)
Im unable to replicate your issue i need to you check that  if it fixed Also add me in discord @kaxun

**Comment by KASUNHapangama** [comment]
i have fixed your issue already working on #20 issue

**Comment by KASUNHapangama** [comment]
fixed with beta 1.3
